<a href="https://colab.research.google.com/github/sarah0211-02/H8_Pertemuan/blob/master/H8_Pertemuan4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

Oleh: Syahrani Nabilla Pardede (PYTN-KS08-013)

##Install Numpy

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
np.__version__

'1.21.6'

##Array

###Membuat Sebuah Array

In [3]:
import numpy as np

a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
# Bisa membuat field array dengan 0s:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
# Atau bisa juga mengisi array dengan 1s:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
# Dapat membuat array dengan berdasarkan range element tertentu

print(np.arange(4))
print(np.arange(0, 10, 2)) # Keterangan (Start, Stop, Step)

[0 1 2 3]
[0 2 4 6 8]


In [9]:
np.arange(2, 29, 5)

array([ 2,  7, 12, 17, 22, 27])

##Add, Remove and Sort

In [10]:
# np.append()
# np.delete()
# np.sort()

# Jika kalian mulai dari array ini:

# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Kalian bisa menambahkan elemen ke array kalian kapan saja dengan np.append().
# Pastikan untuk menentukan array dan elemen yang ingin kalian sertakan

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

np.append(arr, [1, 2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [12]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [14]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

##Shape and Size

In [15]:
# ndarray.ndim()
# ndarray.size()
# ndarray.shape()

# Keterangan :
# 1. ndarray.ndim akan memberi tahu kalian jumlah axes, atau dimensi dari array

# 2. ndarray.size akan memberi tahu kalian jumlah total elemen array. Ini merupakan 
# produk dari elemen shaper array

# 3. ndarray.shape akan menampilkan tuple integer yang menunjukkan jumlah elemen yang 
# disimpan di sepanjang setiap dimensi array.

In [16]:
array_example = np.array([
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ],
    
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ],
    
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ]
])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [17]:
array_example.ndim

3

In [18]:
array_example.size

24

In [19]:
array_example.shape

(3, 2, 4)

In [20]:
arr_one =np.array([[1, 2, 3, 4, 5]])

In [21]:
arr_one.ndim

2

In [22]:
arr_one.size

5

In [23]:
arr_one.shape

(1, 5)

##Reshape

In [24]:
# np.reshape()

# Keterangan :
# Menggunakan np.reshape() akan memberikan bentuk baru ke array tanpa mengubah datanya

In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [27]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

**Catatan**
numpy.reshape(a, newshape, order)

Keterangan :

* a adalah array yang akan di-reshapeed
* newshape adalah bentuk baru yang kalian inginkan, bisa ditentukan antara integer atau tuple integer
* order

##Convert 1D to 2D

In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [29]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [30]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [31]:
# for a column vector, you can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [33]:
# You can use np.expand_dims to add an axis at index position 1 with :

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [34]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=1)
c.shape

(6, 1)

##Indexing dan Slicing 

In [35]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [36]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
# You can easily print all of the values in the array that are less than 5

print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [38]:
five_up = (a >= 5)

print(a[five_up])
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [39]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a % 2 == 0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [40]:
# You can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


##Creating array from existing data

In [41]:
# Slicing Indexing
# np.vstack()
# np.hstack()
# np.hsplit()
# .view()
# .copy()

# array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [43]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [44]:
# a_1:

# array([[1, 1],
    #  [2, 2]])
    
# a_2

# array([[3, 3],
    #  [4, 4]])
    
# Solusi agar dapat menumpuk secara vertikal dengan vstack

a_1 = np.array([[1, 1],
               [2, 2]])

In [45]:
a_2 = np.array([[3, 3],
               [4, 4]])

In [46]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
# atau posisi stack secara horizontal dengan fungsi hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [48]:
# array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
#       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [49]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [50]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [51]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
# You can create a new array object that loks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
# Using the copy method will make a complet copy of the array and it's data (a deep copy)

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

##Basic array operations

* Addition,
* Subtraction,
* Multiplication,
* Division, and
* More

In [54]:
# data - ones
# data * data
# data / data

In [55]:
a = np.array([1, 2, 3, 4])
# 1 + 2 + 3 + 4 = 10

# Add all of the elements in the array
a.sum()

10

In [56]:
# Untuk menambahkan baris atau kolom dalam array 2D, kalian harus menentukan axis.

b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [57]:
# You can sum the rows

b.sum(axis = 0)

array([3, 3])

In [58]:
# You can sum the columns

b.sum(axis = 1)

array([2, 4])

In [59]:
data = np.array([1, 2])
data

array([1, 2])

In [60]:
ones = np.ones(2)
ones

array([1., 1.])

In [61]:
data + ones

array([2., 3.])

In [62]:
data * data

array([1, 4])

In [63]:
data / data

array([1., 1.])

##Broadcasting

In [64]:
data*2

array([2, 4])

##More array operations

* Maximum,
* Minimum,
* Sum,
* Mean,
* Product,
* Standard Deviation, and
* more

In [65]:
# data.max()
# data.min()
# data.sum()

In [66]:
A = np.array([
    [0.45053314, 0.17296777, 0.34376245, 0.5510652],
    [0.54627315, 0.05093587, 0.40067661, 0.55645993],
    [0.12697628, 0.82485143, 0.26590556, 0.56917101]
])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [67]:
A.sum()

4.8595784

In [68]:
A.min()

0.05093587

In [69]:
A.min( axis = 0 )

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [70]:
A.min( axis = 1 )

array([0.17296777, 0.05093587, 0.12697628])

In [71]:
A.std()

0.21392120766089617

##Matrices

###Creating Matrices

In [72]:
# np.array([
#     [1, 2],
#     [3, 4]
# ])

In [73]:
np.ones((3, 2))
np.zeros((3, 2))
np.random.random((2, 3))

print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(np.random.random((2, 3)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.8852653  0.67877167 0.4349062 ]
 [0.34203645 0.31745892 0.72961653]]


###Matrix Arithmetic

In [74]:
data = np.array([
    [1, 2],
    [3, 4]
])

print(data)

[[1 2]
 [3 4]]


In [75]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [76]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [77]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [78]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


###Dot Product

In [79]:
a_1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(a_1)
print(a_1.shape)

a_2 = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [80]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

###Matrix Indexing

In [81]:
data = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0, 1])
print(data[1 : 3])
print(data[0 : 2, 1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


###Matrix Aggregation

In [82]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [83]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


###Transposing and Reshaping

In [84]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [85]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [86]:
data_col = np.array([
    [1, 2, 3, 4, 5, 6]
]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [87]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


###N-Dimensional Array

In [90]:
ndarr = np.array([
    [[1, 2], [3,4]],
    [[5, 6], [7, 8]]
])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [91]:
# np.ones((Jumlah Matriks, Jumlah Baris, Jumlah Kolom))
print(np.ones((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [92]:
# np.zeros((Jumlah Matriks, Jumlah Baris, Jumlah Kolom))
print(np.zeros((4, 3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [93]:
print(np.random.random((4, 3, 2)))

[[[0.74263699 0.77591655]
  [0.20804186 0.03900719]
  [0.49595038 0.07348739]]

 [[0.17474269 0.32998794]
  [0.1780662  0.64868189]
  [0.40844795 0.34970749]]

 [[0.81254177 0.61493222]
  [0.71773735 0.6912118 ]
  [0.28074713 0.68307727]]

 [[0.66034256 0.38398446]
  [0.03721475 0.02945555]
  [0.69371824 0.15402311]]]


###Flaten N-Dimensional Array

In [94]:
arrflat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [95]:
# You can use flattern to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])